src/Entity/Sortie.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SortieRepository")
 */
class Sortie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateHeureDebut;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateLimiteInscription;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbInscriptionsMax;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $infosSortie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="sorties")
     */
    private $organisateur;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="sortiesUtilisateur")
     */
    private $inscriptions;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Etat", inversedBy="sorties")
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lieu", inversedBy="sorties")
     */
    private $lieu;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateHeureDebut()
    {
        return $this->dateHeureDebut;
    }

    public function setDateHeureDebut($dateHeureDebut): self
    {
        $this->dateHeureDebut = $dateHeureDebut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateLimiteInscription()
    {
        return $this->dateLimiteInscription;
    }

    public function setDateLimiteInscription($dateLimiteInscription): self
    {
        $this->dateLimiteInscription = $dateLimiteInscription;

        return $this;
    }

    public function getNbInscriptionsMax(): ?int
    {
        return $this->nbInscriptionsMax;
    }

    public function setNbInscriptionsMax(int $nbInscriptionsMax): self
    {
        $this->nbInscriptionsMax = $nbInscriptionsMax;

        return $this;
    }

    public function getInfosSortie(): ?string
    {
        return $this->infosSortie;
    }

    public function setInfosSortie(?string $infosSortie): self
    {
        $this->infosSortie = $infosSortie;

        return $this;
    }

    public function getOrganisateur(): ?User
    {
        return $this->organisateur;
    }

    public function setOrganisateur(?User $organisateur): self
    {
        $this->organisateur = $organisateur;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getListeInscrit(): Collection
    {
        return $this->inscriptions;
    }

    public function addEstInscrit(User $participant): self
    {
        if (!$this->inscriptions->contains($participant)) {
            $this->inscriptions[] = $participant;
        }

        return $this;
    }

    public function removeEstInscrit(User $participant): self
    {
        if ($this->inscriptions->contains($participant)) {
            $this->inscriptions->removeElement($participant);
        }

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }
}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\Etat;
use App\Entity\Site;
use App\Entity\Sortie;
use App\Entity\Ville;
use App\Entity\Lieu;
use App\Form\NewLieuType;
use App\Form\NewSortieType;
use App\Form\VilleType;
use App\Repository\EtatRepository;
use App\Repository\SiteRepository;
use App\Repository\SortieRepository;
use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SortieController extends AbstractController
{

    public const CREATION = "creation";
    public const MODIFICATION = "modification";
    public const ANNULATION = "annulation";

    /**
     * @Route("/sorties/list", name="sorties")
     * @param SortieRepository $repoSorties
     * @param SiteRepository $repoSites
     * @return Response
     * @throws Exception
     */
    public function listeSorties(SortieRepository $repoSorties, SiteRepository $repoSites, Request $request)
    {
        $userCourant = $this->getUser() == null ? -1 : $this->getUser()->getId();
        $filtre = [];
        $rechercheForm = $this->createFormBuilder(array())
            ->add('site', EntityType::class, [
                'class' => 'App\Entity\Site',
                'query_builder' => function (SiteRepository $siteRepository) {
                    return $siteRepository->createQueryBuilder('site')->orderBy('site.nom', 'ASC');
                },
                'choice_label' => function (Site $site) {
                    return $site->getNom();
                },
                'placeholder' => 'Tous les sites',
                'required' => false
            ])
            ->add('nomContient', TextType::class, [
                'required' => false
            ])
            ->add('dateDebut', TextType::class, [
                'required' => false
            ])
            ->add('dateFin', TextType::class, [
                'required' => false
            ])
            ->add('organisateur', CheckboxType::class, [
                'required' => false
            ])
            ->add('inscrit', CheckboxType::class, [
                'required' => false
            ])
            ->add('pasInscrit', CheckboxType::class, [
                'required' => false
            ])
            ->add('passees', CheckboxType::class, [
                'required' => false
            ])
            ->add('idUser', HiddenType::class, [
                'attr' => ['value' => $userCourant]
            ])
            ->getForm();
        $rechercheForm->handleRequest($request);
        $filtre = $rechercheForm->getData();

        if ($rechercheForm->isSubmitted() && $rechercheForm->isValid() || !empty($filtre)) {
            $sorties = $repoSorties->rechercherSorties($filtre);
        } else {
            // On gère le cas du filtre non renseigné,
            $sorties = $repoSorties->rechercherSorties(array());
        }

        $sortiesUtilisateur = $repoSorties->listeSortieUtilisateur($userCourant);
        $nbInscritsParSortie = [];
        $listeSites = $repoSites->findAll();
        foreach ($sorties as $sortie) {
            $nbInscritsParSortie[$sortie->getId()] = $repoSorties->nbInscriptions($sortie);
        }


        return $this->render('sortie/liste.html.twig', [
            'rechercheForm' => $rechercheForm->createView(),
            'sorties' => $sorties,
            'listeSites' => $listeSites,
            'sortiesUtilisateur' => $sortiesUtilisateur,
            'nbInscritsParSortie' => $nbInscritsParSortie,
            'filtre' => $filtre,
        ]);
    }

    /**
     * @Route("/nouvelle-sortie/{id}", name="nouvelleSortie")
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @param EtatRepository $repoEtats
     * @return RedirectResponse|Response
     * @throws DBALException
     */
    public function nouvelleSortie(Request $request, EntityManagerInterface $entityManager, EtatRepository $repoEtats, $id, SortieRepository $sortieRepository)
    {
        $action = "";

        if($id == -1){
            $action = self::CREATION;
            $sortie = new Sortie();
            $lieu = new Lieu();
            $ville = new Ville();
        }
        else{
            $action = self::MODIFICATION;
            $formatDates = 'd/m/Y H:i';
            $sortie = $sortieRepository->find($id);
            $sortie->setDateLimiteInscription(date_format($sortie->getDateLimiteInscription(), $formatDates));
            $sortie->setDateHeureDebut(date_format($sortie->getDateHeureDebut(), $formatDates));
            $lieu = $sortie->getLieu();
            $ville = $lieu->getVille();
        }


        $repoVille = $entityManager->getRepository(Ville::class);
        $villes = $repoVille->findAll();
        $repoLieu = $entityManager->getRepository(Lieu::class);
        $lieux = $repoLieu->findAll();

        $newSortieForm = $this->createForm(NewSortieType::class, $sortie);
        $newLieuForm = $this->createForm(NewLieuType::class, $lieu);
        $newVilleForm = $this->createForm(VilleType::class, $ville);


        $newSortieForm->handleRequest($request);
        $newLieuForm->handleRequest($request);
        $newVilleForm->handleRequest($request);

        if ($newVilleForm->isSubmitted() && $newVilleForm->isValid()) {
            $entityManager->persist($ville);
            $entityManager->flush();
        }

        if ($newLieuForm->isSubmitted() && $newLieuForm->isValid()) {
            $entityManager->persist($lieu);
            $entityManager->flush();
        }

        if ($newSortieForm->isSubmitted() && $newSortieForm->isValid()) {
            $organisateur = $this->getUser();
            $sortie->setOrganisateur($organisateur);
            $etatOuverte = $repoEtats->findOneBy(array('libelle' => Etat::OUVERTE));
            $etatCreee = $repoEtats->findOneBy(array('libelle' => Etat::CREEE));

            if ($newSortieForm->get('publier')->isClicked()) {
                $sortie->setEtat($etatOuverte);
            } else {
                // On vérifie simplement que la sortie n'est pas déjà publié quand on la modifie
                if($sortie->getEtat() !== $etatOuverte)
                {
                    $sortie->setEtat($etatCreee);
                }
            }

            // On gère les dates
            $formatDates = 'd/m/Y H:i';

            $dateSortie = date_create_from_format($formatDates, $newSortieForm->get('dateHeureDebut')->getData());
            $dateLimite = date_create_from_format($formatDates, $newSortieForm->get('dateLimiteInscription')->getData());
            $sortie->setDateHeureDebut($dateSortie);
            $sortie->setDateLimiteInscription($dateLimite);

            $entityManager->persist($sortie);


            if($sortie->getEtat() === $etatOuverte)
            {
                $sortieRepository->gererEvenements($action, $sortie->getId());
            }

            $entityManager->flush();

            $this->addFlash("success", "Votre sortie a bien été créée !");
            return $this->redirectToRoute("sorties");
        }
        return $this->render('sortie/nouvelleSortie.html.twig', [
            'newSortieForm' => $newSortieForm->createView(),
            'newLieuForm' => $newLieuForm->createView(),
            'newVilleForm' => $newVilleForm->createView(),
            'villes' => $villes,
            'lieux' => $lieux
        ]);
    }

    /**
     * @Route("/inscription-sortie/{id}", name="inscriptionSortie")
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @param SortieRepository $repoSorties
     * @param $id
     * @return RedirectResponse
     * @throws Exception
     */
    public function inscriptionSortie(Request $request, EntityManagerInterface $entityManager, SortieRepository $repoSorties, $id)
    {
        $sortieCourante = $repoSorties->find($id);

        $maintenant = new \DateTime();
        if($sortieCourante->getListeInscrit()->count() < $sortieCourante->getNbInscriptionsMax() && $maintenant<$sortieCourante->getDateLimiteInscription()) {
            $sortieCourante->addEstInscrit($this->getUser());
            $entityManager->persist($sortieCourante);
            $entityManager->flush();
        }
        else{
            if($sortieCourante->getListeInscrit()->count() == $sortieCourante->getNbInscriptionsMax()) {
                $this->addFlash('error', "Nombre maximum d'inscrits atteint");
            }
            if($maintenant>=$sortieCourante->getDateLimiteInscription()) {
                $this->addFlash('error', "Date limite d'inscription dépassée");
            }
        }

        return $this->redirectToRoute("sorties");
    }

    /**
     * @Route("/publier-sortie/{id}", name="publierSortie")
     * @throws DBALException
     */
    public function publierSortie(Request $request, EntityManagerInterface $entityManager, SortieRepository $repoSorties, EtatRepository $repoEtats, $id)
    {

        $sortieCourante = $repoSorties->find($id);

        $sortieCourante->setEtat($repoEtats->findOneBy(array('libelle' => Etat::OUVERTE)));
        $entityManager->persist($sortieCourante);

        // On crée l'événement associé
        $repoSorties->gererEvenements(self::CREATION, $sortieCourante->getId());

        $entityManager->flush();

        return $this->redirectToRoute("sorties");
    }

    /**
     * @Route("/desister-sortie/{id}", name="desistementSortie")
     */

templates/sortie/DetailsSortie.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Details sortie
{% endblock %}


{% block main %}
    <style>
        table.table.table-striped > thead > tr > th {
            border: none;
            color: #fffffe;
        }

        table.table.table-striped > tbody > tr > th {
            border: none;
            color: #fffffe;
        }

        table.table.table-striped > tbody > tr > td {
            border: none;
            color: #fffffe;
        }

        @media (min-width: 1200px) {
            .container {
                max-width: 40%;
            }
        }
    </style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm- 10 col-md-8 col-lg-6 p-3">
                <h1 class="text-center">{{ sortie.nom }}</h1>
            </div>
        </div>
        <br>
        <div class="row justify-content-center">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th class="col-12 col-md-3" scope="col">Intitulé :</th>
                    <th class="col-12 col-md-3" scope="col">{{ sortie.nom }}</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">Date et heure de la sortie :</th>
                    <td>{{ sortie.dateHeureDebut|date("d/m/Y H:i") }}</td>
                </tr>
                <tr>
                    <th scope="row">Date limite d'inscription :</th>
                    <td>{{ sortie.dateLimiteInscription|date("d/m/Y H:i") }}</td>
                </tr>
                <tr>
                    <th scope="row">Nombre de place restantes :</th>
                    <td>{{ sortie.nbInscriptionsMax - repo.nbInscriptions(sortie) }}</td>
                </tr>
                <tr>
                    <th scope="row">Durée :</th>
                    <td>{{ sortie.duree }} minutes</td>
                </tr>
                <tr>
                    <th scope="row">Description et info :</th>
                    <td>{{ sortie.infosSortie }}</td>
                </tr>
                <tr>
                    <th scope="row">Lieu :</th>
                    <td>{{ sortie.lieu.nom }}</td>
                </tr>
                <tr>
                    <th scope="row">Rue :</th>
                    <td>{{ sortie.lieu.rue }}</td>
                </tr>
                <tr>
                    <th scope="row">Ville :</th>
                    <td>{{ sortie.lieu.ville.nom }}</td>
                </tr>
                <tr>
                    <th scope="row">Code postal :</th>
                    <td>{{ sortie.lieu.ville.codePostal }}</td>
                </tr>
                <tr>
                    <th scope="row">Coordonées GPS</th>
                    <td>{{ sortie.lieu.latitude }} - {{ sortie.lieu.longitude }}</td>
                </tr>
                <tr>
                    <th scope="row">Liste des inscrits :</th>
                    <td>
                        <a href={{ path('profile',{id:sortie.organisateur.id} ) }}> {{ sortie.organisateur.username }}
                            (Organisateur) </a>
                        <br>
                        {% set inscrits = sortie.listeInscrit %}
                        {% for inscrit in inscrits %}
                            <a href="{{ path('profile', {id:inscrit.id}) }}"> {{ inscrit.username }} </a>
                        {% endfor %}
                    </td>
                </tr>
                </tbody>
            </table>

            {% set CREEE = constant('App\\Entity\\Etat::CREEE') %}
            {% if (sortie.dateHeureDebut > maintenant or sortie.etat.libelle == CREEE )and sortie.organisateur.id == app.user.id %}
                <a href="{{ path('nouvelleSortie', {'id':sortie.id}) }}">
                    <button class="btn btn-block" style="background-color: #ff8906; color:#fffffe">
                        Modifier la sortie
                    </button>
                </a>
            {% endif %}
        </div>
    </div>


{% endblock %}

templates/sortie/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des sorties{% endblock %}

{% block main %}
    <style>
        .card {
            background: transparent;
            color: #fffffe;
        }
        table.table.table-striped>thead>tr>th{
            color: #fffffe;
            border:none;
        }
        table.table.table-striped>tbody>tr>th{
            color: #fffffe;
            border:none;
        }
        table.table.table-striped>tbody>tr>td{
            color: #fffffe;
            border:none;
        }
        .annulee{
            color: red !important;
        }
    </style>
    {% set CREEE = constant('App\\Entity\\Etat::CREEE') %}
    {% set OUVERTE = constant('App\\Entity\\Etat::OUVERTE') %}
    {% set CLOTUREE = constant('App\\Entity\\Etat::CLOTUREE') %}
    {% set EN_COURS = constant('App\\Entity\\Etat::EN_COURS') %}
    {% set PASSEE = constant('App\\Entity\\Etat::PASSEE') %}
    {% set ANNULEE = constant('App\\Entity\\Etat::ANNULEE') %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm- 10 col-md-8 col-lg-6 p-3">
                <h1 class="text-center">Trouver une Sortie </h1>
            </div>
        </div>
        {% block form %}
            <div id="rechercheAvancee">
                {{ form_start(rechercheForm,{ 'attr': {'class': 'card'} }) }}
                <!-- site -->
                <div class="form-group row">
                    <div class="col-12 col-sm-2  col-form-label">
                        <label for="form_site">Site</label>
                    </div>
                    <div class="erreur_form">
                        {{ form_errors(rechercheForm.site) }}
                    </div>
                    <div class="col-12 col-sm-10">
                        {{ form_widget(rechercheForm.site, { 'attr': {'class': 'form-control'} }) }}
                    </div>
                </div>
                <!-- nom contient -->
                <div class="form-group row">
                    <div class="col-12 col-sm-2 col-form-label">
                        <label for="nomContient">Le nom contient</label>
                    </div>
                    <div class="erreur_form">
                        {{ form_errors(rechercheForm.nomContient) }}
                    </div>
                    <div class="col-sm-10">
                        {{ form_widget(rechercheForm.nomContient, { 'attr': {'class': 'form-control', 'placeholder':'recherche', 'type':'search'} }) }}
                    </div>
                </div>

                <div class="datesLiees form-group row">
                    <!-- entre début -->
                    <div class="col-12 col-md-6">
                        <div class=" col-12 col-md-6 col-form-label" style="padding-left: 0">
                            <label for="form_dateDebut">Entre le</label>
                        </div>
                        <div>
                            <div class="erreur_form">
                                {{ form_errors(rechercheForm.dateDebut) }}
                            </div>
                            <div class="input-group date" id="form_dateDebut" data-target-input="nearest">
                                {{ form_widget(rechercheForm.dateDebut, { 'attr': {'class': 'form-control datetimepicker-input', 'data-target':'#form_dateDebut'} }) }}
                                <div class="input-group-append" data-target="#form_dateDebut"
                                     data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="col-12 col-sm-2 col-form-label" style="padding-left: 0">
                            <label for="form_dateFin">Et le</label>
                        </div>

                        <div>
                            <div class="erreur_form">
                                {{ form_errors(rechercheForm.dateFin) }}
                            </div>

                            <div class="input-group date" id="form_dateFin" data-target-input="nearest">
                                {{ form_widget(rechercheForm.dateFin, { 'attr': {'class': 'form-control datetimepicker-input', 'data-target':'#form_dateFin'} }) }}
                                <div class="input-group-append" data-target="#form_dateFin"
                                     data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-7 col-md-6" >
                        <!-- organisateur -->
                        <div class="form-check row">
                            <div class="erreur_form">
                                {{ form_errors(rechercheForm.organisateur) }}
                            </div>
                            {{ form_widget(rechercheForm.organisateur, { 'attr': {'class': 'form-check-input', 'type':'checkbox'} }) }}
                            <label for="form_organisateur" class="form-check-label">Sorties dont je suis
                                l'organisateur/trice</label>
                        </div>
                        <!-- inscrit -->
                        <div class="form-check row">
                            <div class="erreur_form">
                                {{ form_errors(rechercheForm.inscrit) }}
                            </div>
                            {{ form_widget(rechercheForm.inscrit, { 'attr': {'class': 'form-check-input', 'type':'checkbox'} }) }}
                            <label for="form_inscrit" class="form-check-label">Sorties auxquelles je suis
                                inscrit/e</label>
                        </div>
                        <!-- pas inscrit -->
                        <div class="form-check row">
                            <div class="erreur_form">
                                {{ form_errors(rechercheForm.pasInscrit) }}
                            </div>
                            {{ form_widget(rechercheForm.pasInscrit, { 'attr': {'class': 'form-check-input', 'type':'checkbox'} }) }}
                            <label for="form_pasInscrit" class="form-check-label">Sorties auxquelles je ne suis pas
                                inscrit/e</label>
                        </div>
                        <!-- passées -->
                        <div class="form-check row">
                            <div class="erreur_form">
                                {{ form_errors(rechercheForm.passees) }}
                            </div>
                            {{ form_widget(rechercheForm.passees, { 'attr': {'class': 'form-check-input', 'type':'checkbox'} }) }}
                            <label for="form_passees" class="form-check-label">Sorties passées</label>
                        </div>
                    </div>
                    <br>
                    <div class="col-12 col-sm-5 col-md-6 d-flex align-items-end">
                        <button type="submit" class="btn btn-block" style="background-color: #ff8906; color:#fffffe">
                            Rechercher
                        </button>
                    </div>
                    {{ form_end(rechercheForm) }}
                </div>
            </div>
        {% endblock %}

        <br>
        <hr style="background: #e53170">
        <br>

        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}

        <table class="table table-striped" id="listeSorties">
            <thead>
            <tr>
                <th scope="col">Nom de la sortie</th>
                <th scope="col">Date de la sortie</th>
                <th scope="col">Clôture</th>
                <th scope="col">Inscrits / Places</th>
                <th scope="col">Etat</th>
                <th scope="col">Inscrit ?</th>
                <th scope="col">Organisateur</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for sortie in sorties %}
                {% if app.user != null %}
                    {% if sortie.etat.libelle != CREEE or sortie.organisateur.id == app.user.id %}
                        {% if sortie.etat.libelle == ANNULEE %}
                            {# ici on met une variable a annulee si la sortie est annulee pour pouvoir faire un affichage particulié#}
                            {% set annulee = 'annulee' %}
                        {% endif %}
                        {% if sortie.etat.libelle != ANNULEE %}
                            {# si la sortie n'est pas annulée affichage normal#}
                            {% set annulee = '' %}
                        {% endif %}

                        <tr>
                            <th scope="row"><a href="{{ path('detailsSortie' , {id:sortie.id}) }}"> {{ sortie.nom }} </a></th>
                            <td>{{ sortie.dateHeureDebut|date("d/m/Y H:i") }}</td>
                            <td>{{ sortie.dateLimiteInscription|date("d/m/Y H:i") }}</td>
                            <td>{{ nbInscritsParSortie[sortie.id] }} / {{ sortie.nbInscriptionsMax }}</td>
                            <td class= {{ annulee }}>{{ sortie.etat.libelle }}</td>
                            <td>
                                {% if sortie in sortiesUtilisateur %}
                                    <i class="fal fa-beer"></i>
                                {% endif %}
                            </td>
                            <td><a href="{{ path('profile',{id:sortie.organisateur.id} ) }}">  {{ sortie.organisateur.username }} </a></td>

                            <td class="boutonsAction">
                                {% if sortie.etat.libelle == CREEE and sortie.organisateur.id == app.user.id %}
                                    <a href="{{ path('publierSortie', {'id':sortie.id}) }}">
                                        <button name="publier" value="publier" class="btn-sm" style="background: #fffffe; color: #0f0e17; border:none"><i class="fas fa-paper-plane"></i></button>
                                    </a>
                                {% endif %}
                                {% if (sortie.etat.libelle == CREEE or sortie.etat.libelle == OUVERTE) and sortie.organisateur.id == app.user.id %}
                                    <a href="#" data-action="{{ path('annulerSortie', {'id':sortie.id}) }}"
                                       data-toggle="modal" data-target="#confirmer-annulation"
                                       data-contenu="{{ sortie.nom }}">
                                        <button name="annuler" value="annuler" class="btn-sm" style="background: #fffffe; color: #0f0e17; border:none"><i class="fas fa-trash-alt"></i></button>
                                    </a>

                                {% endif %}
                                {% if sortie not in sortiesUtilisateur and sortie.etat.libelle == OUVERTE and sortie.organisateur.id != app.user.id %}
                                    <a href="{{ path('inscriptionSortie', {'id':sortie.id}) }}">
                                        <button name="s-inscrire" value="s'inscrire" class="btn-sm shadow" style="color: #fffffe; background: #23bf5d; border: none;"><i class="fal fa-beer"></i></button>
                                    </a>
                                {% endif %}
                                {% if sortie in sortiesUtilisateur and sortie.etat.libelle == OUVERTE %}
                                    <a href="{{ path('desistementSortie', {'id':sortie.id}) }}">
                                        <button name="se-desister" value="se-desister" class="btn-sm shadow" style="color: #fffffe; background: #C82829; border: none ;padding-left: 16%; padding-right: 16%"><i class="fal fa-times"></i></button>
                                    </a>
                                {% endif %}

                            </td>
                        </tr>
                    {% endif %}
                {% endif %}
            {% endfor %}
            </tbody>
        </table>

        {#Ici, on ajoute la modale de confirmation#}
        <div class="modal fade" id="confirmer-annulation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>

        {% block javascripts %}
            {{ parent() }}
            <script type="text/javascript" src="{{ asset('js/confirmationAnnulation.js') }}"></script>
        {% endblock %}
    </div>
{% endblock %}